const $=id=>document.getElementById(id);let profiles={};let currentDomain='';
function send(message){return new Promise(resolve=>chrome.runtime.sendMessage(message,resolve));}
function status(m){$('status').textContent=m||'';clearTimeout(status.t);status.t=setTimeout(()=>$('status').textContent='',3200);}
function render(){const q=$('search').value.trim().toLowerCase();const box=$('domains');box.innerHTML='';const list=Object.entries(profiles).filter(([d])=>!q||d.includes(q)).sort(([a],[b])=>a.localeCompare(b));if(!list.length){box.innerHTML='<div class="empty">No protected domains found.</div>';return;}for(const[d,p]of list){const row=document.createElement('div');row.className='domain-row';const info=document.createElement('div');info.className='domain-info';const name=document.createElement('div');name.className='domain-name';name.textContent=d;const badge=document.createElement('div');badge.className='badge';badge.textContent=(p.mode||'custom').toUpperCase()+' • '+Object.values(p).filter(v=>v===true).length+' protections';info.append(name,badge);const rm=document.createElement('button');rm.className='remove';rm.textContent='×';rm.title='Remove protection';rm.onclick=async()=>{await send({type:'remove-profile',domain:d});delete profiles[d];render();status('Removed '+d);};row.append(info,rm);box.appendChild(row);}}
async function load(){const tabs=await chrome.tabs.query({active:true,currentWindow:true});const url=tabs[0]?.url||'';currentDomain=CorsairSecurity.extractHostname(url);$('currentDomain').textContent=currentDomain||'Unavailable on this page';profiles=(await send({type:'get-profiles'}))?.profiles||{};render();const s=(await send({type:'get-settings'}))?.settings||{};$('toggleBypass').classList.toggle('on',s.resolverEnabled===true);$('toggleBypass').textContent=s.resolverEnabled?'ON':'OFF';const local=await chrome.storage.local.get('theme');const light=local.theme==='light';document.body.classList.toggle('light',light);$('toggleMode').textContent=light?'☾':'☀';}
$('addCurrent').onclick=async()=>{if(!currentDomain){status('This page cannot be protected.');return;}const r=await send({type:'protect-current-domain',url:`https://${currentDomain}/`});if(!r?.ok){status('Could not protect '+currentDomain);return;}profiles[currentDomain]=r.profile;render();status('🛡 '+currentDomain+' → FORTRESS • ALL PROTECTIONS ON');};
$('toggleBypass').onclick=async()=>{const s=(await send({type:'get-settings'}))?.settings||{};const next=!s.resolverEnabled;await send({type:'patch-settings',patch:{resolverEnabled:next}});await chrome.storage.local.set({ouoBypassEnabled:next});$('toggleBypass').classList.toggle('on',next);$('toggleBypass').textContent=next?'ON':'OFF';status('Safe Redirect Resolver '+(next?'enabled':'disabled'));};
$('toggleMode').onclick=async()=>{const d=await chrome.storage.local.get('theme');const next=d.theme==='light'?'dark':'light';await chrome.storage.local.set({theme:next});document.body.classList.toggle('light',next==='light');$('toggleMode').textContent=next==='light'?'☾':'☀';};
$('search').oninput=render;$('openDashboard').onclick=()=>chrome.tabs.create({url:chrome.runtime.getURL('dashboard.html')});load().catch(e=>status(e.message||String(e)));
